### PR TITLE
Migrate styles to LESS and add autoprefixer

### LINKED ISSUE #25: Migrate styles to LESS, add autoprefixer
## Deliverables

- Reporter styles using the power of LESS
- No more duplicated prefixed styles

#### Prerequisites
- [LESS](http://lesscss.org/)
- `webpack`
  - [less-loader](https://github.com/webpack/less-loader)
  - [autoprefixer](https://github.com/postcss/autoprefixer#webpack)

#### TODO
- [x] TBD

cc: @adela-istrate-hs

### PR DESCRIPTION
**Pull request by adela-istrate-hs**
Closes #25

### CODE REVIEW

**Comment by adela-istrate-hs** [comment]
@flavius-tirnacop-hs @andrei-picus-hs 
Can you review?

**Comment by flavius-tirnacop-hs** [comment]
You have conflicts

**Comment by adela-istrate-hs** [comment]
@flavius-tirnacop-hs  I resolved the conflicts.

**Comment by adela-istrate-hs** [comment]
@flavius-tirnacop-hs @valentin-radulescu-hs Can you review?

**Comment by flavius-tirnacop-hs** [comment]
LGTM

**Comment by valentin-radulescu-hs** [comment]
Let's go one step forward here and split the styles into components. You'd have something like
```
styles/constants/colors.less
styles/components/header.less
```

Then in each component import its styles and you can use https://github.com/webpack/extract-text-webpack-plugin to generate a single output css file.

**Comment by adela-istrate-hs** [comment]
@valentin-radulescu-hs Is this ok?

**Comment by valentin-radulescu-hs** [comment]
LGTM

**Pull request merged**
